### ISSUE TITLE
Remove code duplication via CSS cascading

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#659]
issue goal: remove the code duplication present on https://github.com/SAP/techne/blob/v2.0/dist/css/techne-all.css

On the final generated CSS we distribute we have code duplication. Examples:
https://github.com/SAP/techne/blob/v2.0/dist/css/techne-all.css#L186

Code Extract
```css
.tn-primary-nav__directory {
  display: inline-block;
  margin-bottom: 0;
  padding: 0 20px 0 0; }

.tn-primary-nav__index {
  display: inline-block;
  margin-bottom: 0;
  padding: 0 20px;
  vertical-align: top; }

...
```

Line [186](https://github.com/SAP/techne/blob/v2.0/dist/css/techne-all.css#L186) and [187](https://github.com/SAP/techne/blob/v2.0/dist/css/techne-all.css#L186) are duplicated on the following styles declarations.

This result on unused CSS code been downloaded and parsed.

### Solution

Use the cascade by separating in main and secondary classes 
```ccs 
.tn-primary-nav .tn-primary-nav-index
```
