### ISSUE TITLE
Decide a color management solution

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#854]
Goal: decide a way to store and change the color palette that is fluid and smooth for Design and also for Development.

### Current situation
We have only the wiki page with a PSD/PNG file and a table
https://github.com/SAP/techne/wiki/Colors#visual-representation

### Pain points
1. Changing the a single color or adding a group cascades to
    1. Change the PSD/PNG
    2. Change the wiki
    3. Change the SCSS code
2. The PSD/PNG and wiki cannot be reused by the website or the library

**Comment by joseegm** [comment]
One solution will be using 
http://opencolor.tools/

That way the palette is define in OCO format - https://github.com/opencolor-tools/opencolor-spec/blob/master/specification.md

This is how the Techne Pallete looks like in OCO
````yaml
oct/
  defaultView: stack
 
Primary:
  Shade 1: #006FBB
  Shade 2: #27394F
Action:
  Shade 1: #009CDF
  Shade 2: #00A5EC
  Shade 3: #0093D1
  Shade 4: #008AC4
Text:
  Shade 1: #21262C
  Shade 2: #7F90A4
  Shade 3: #63758B
Text-Inverse:
  Shade 1: #FFFFFF
  Shade 2: #F6F8F9
  Shade 3: #EEF1F3
Neutral:
  Shade 1: #F9FBFC
  Shade 2: #D7D7D7
  Shade 3: #CCDAEB
  Shade 4: #8A8FA1
  Shade 5: #A8BFE3
  Shade 6: #A8BFE3
Backgrounds:
  Shade 1: #FFFFFF
Success: 
  Shade 1: #61BF33
Warning:
  Shade 1: #E96B1A
Error:
  Shade 1: #DF1919
````
And can be visually represented differently 

| Minimal | Cards |
|---|---|
| ![screen shot 2017-08-01 at 13 49 19](https://user-images.githubusercontent.com/22662903/28823975-52c98598-76c0-11e7-9683-45e48a0c47d0.png) | ![screen shot 2017-08-01 at 13 49 33](https://user-images.githubusercontent.com/22662903/28823981-5982e064-76c0-11e7-8417-d8061709a508.png) |

### Advantages
1. One single source for the colors in readable format (.OCO)
2. Open Color App can be used to create themes as well
3. Export to SCSS for use in the library
4. Export to JSON to use on the website to generate visualize the colors
5. Library in JS to parse and use the OCO file. Can be integrated on the toolchain
